/*
 * Copyright (C) 2014 MediaMath, Inc. <http://www.mediamath.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package mediamath.metrics

import org.scalatest._
import com.codahale.metrics._
import com.fasterxml.jackson.module.scala._
import com.fasterxml.jackson.databind.ObjectMapper
import collection._
import scala.collection.immutable.ListMap
import mediamath.metrics.QasinoReporter.AuthenticationException

class QasinoReporterSpec extends FlatSpec with Matchers {

  val QASINO_HOST_PROPERTY = "test_qasino_host"
  val QASINO_HOST_OPTION:Option[String]= scala.util.Properties.propOrNone(QASINO_HOST_PROPERTY)

  val QASINO_USER_PROPERTY = "test_qasino_user"
  val QASINO_USER = scala.util.Properties.propOrElse(QASINO_USER_PROPERTY, "eng")

  val QASINO_PASSWORD_PROPERTY = "test_qasino_password"
  val QASINO_PASSWORD = scala.util.Properties.propOrElse(QASINO_PASSWORD_PROPERTY, "1qa2ws3e")

  def createBuilderForTestHost(registry:MetricRegistry): Option[QasinoReporter.Builder] = QASINO_HOST_OPTION map { qasinoHost =>
    QasinoReporter.forRegistry(registry)
      .withHost(qasinoHost)
      .withSecure()
      .withUsername(QASINO_USER)
      .withPassword(QASINO_PASSWORD)
      .withPersist()
  }

	// name sanitation checks
	val sep = QasinoReporter.registryNameSeparator
	"A sanitized registry name" should "replace non-alphanumeric characters with underscores" in {
		QasinoReporter.sanitizeString("testing.abc") should be ("testing" + sep + "abc")
	}
	it should "change all uppercase characters to lowercase" in {
		QasinoReporter.sanitizeString("tEsT") should be ("test")
	}

	{
		// JSON validation
		val mapper = new ObjectMapper()
		mapper.registerModule(DefaultScalaModule)
		val counter1 = new Counter
		val counter1name = "testing_abc"
		val counter2 = new Counter
		counter2.inc(100)
		val counter2name = "testing_def"
		val metrics = new MetricRegistry
		metrics.register(MetricRegistry.name(counter1name), counter1)
		metrics.register(MetricRegistry.name(counter2name), counter2)

		"The JSON generated by two separated metrics" should "be reported separately" in {
			val groupPrefix = "nothing_in_common"
			val reporter = QasinoReporter.forRegistry(metrics).withGroupings(Set(groupPrefix)).build()
			val jsonStrSeq = reporter.getJson(ListMap[String, Metric](counter1name -> counter1, counter2name -> counter2))
			jsonStrSeq.size should be (2)
		}

    "The JSON generated by two metrics with the same group" should "be reported together" in {
			val groupPrefix = "testing"
			val reporter = QasinoReporter.forRegistry(metrics).withGroupings(Set(groupPrefix)).build()
			val jsonStrSeq = reporter.getJson(ListMap[String, Metric](counter1name -> counter1, counter2name -> counter2))
			jsonStrSeq.size should be (1)
		}

		// Check JSON values
		{
			class IntGauge(value: Int) extends Gauge[Int] {
				def getValue = value
			}

			metrics.register("testing_gauge", new IntGauge(100))
			metrics.register("testing_meter", new Meter())
			metrics.register("testing_timer", new Timer())
			val groupPrefix = "testing"
			val reporter = QasinoReporter.forRegistry(metrics).withGroupings(Set(groupPrefix)).withVerbosity(1).build()
			val jsonStrSeq = reporter.getJson(reporter.combineMetricsToMap()).toSeq
			val dataMap = mapper.readValue(jsonStrSeq(0), classOf[Map[String, Any]])
			val tableDataMap = dataMap.getOrElse("table", {}).asInstanceOf[Map[String, Any]]

			"The op value" should "be add_table_data" in {
				"add_table_data" should equal { dataMap("op") }
			}

			"The tablename value" should "be " + groupPrefix in {
				groupPrefix should equal { tableDataMap("tablename") }
			}

			val correctColumnNames = List(
        "host",
        "abc_count",
        "def_count",
        "gauge_value",
        "meter_count",
        "meter_mean_rate",
        "meter_rate_unit",
        "meter_m1_rate",
        "meter_m5_rate",
        "meter_m15_rate",
        "timer_count",
        "timer_min_time",
        "timer_max_time",
        "timer_mean_time",
        "timer_time_unit",
        "timer_stddev_time",
        "timer_p50_time",
        "timer_p75_time",
        "timer_p95_time",
        "timer_p98_time",
        "timer_p99_time",
        "timer_p999_time",
        "timer_mean_rate",
        "timer_rate_unit",
        "timer_m1_rate",
        "timer_m5_rate",
        "timer_m15_rate"
      )

			"The column_names" should "be " + correctColumnNames in {
				tableDataMap("column_names") should equal (correctColumnNames)
			}

      val correctColumnTypes = List(
        "text",
        "integer",
        "integer",
        "text",
        "integer",
        "real",
        "text",
        "real",
        "real",
        "real",
        "integer",
        "real",
        "real",
        "real",
        "text",
        "real",
        "real",
        "real",
        "real",
        "real",
        "real",
        "real",
        "real",
        "text",
        "real",
        "real",
        "real"
      )
			"The column_types" should "be " + correctColumnTypes in {
				tableDataMap("column_types") should be (correctColumnTypes)
			}
		}
	}

  {
    val badPassword = "bogusPassWord"

    class StringGauge(value: String) extends Gauge[String] {
      def getValue = value
    }
    class LongGauge(value: Long) extends Gauge[Long] {
      def getValue = value
    }

    val metrics = new MetricRegistry
    val markTime = System.currentTimeMillis
    println(s"Timestamp: $markTime")
    metrics.register("bar.stringGauge", new StringGauge("i'm a little teapot"))
    metrics.register("bar.longGauge", new LongGauge(markTime))
    val counter1 = new Counter
    counter1.inc(100)
    metrics.register("bar.counters.counter1", counter1)
    val counter2 = new Counter
    counter2.inc(200)
    metrics.register("bar.counters.counter2", counter2)
    val counterShouldBeDeleted = new Counter
    counterShouldBeDeleted.inc(100)
    metrics.register("bar.counters.counterShouldBeDeleted", counter1)

    for ( builder <- createBuilderForTestHost(metrics) ) {
      it should "authenticate using proper username and password" in {
        val reporter = builder
          .withGroupings(Set("bar", "bar.counters"))
          .build()

        // Add another counter after registering the metrics
        val counter3 = new Counter
        counter3.inc(300)
        metrics.register("bar.counters.counter3", counter3)
        metrics.remove("bar.counters.counterShouldBeDeleted")

        noException should be thrownBy {
          reporter.reportThrowExceptions()
        }
      }

      it should "fail to authenticate if a bad password is used" in {
        val reporter = builder
          .withGroupings(Set("bar", "bar.counters"))
          .withPassword(badPassword)
          .build()

        an [AuthenticationException] should be thrownBy {
          reporter.reportThrowExceptions()
        }
      }
    }
  }
}
